// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TestData.Models;

namespace TestData.Data
{
    public partial class TestAppIDbContext
    {
        private ITestAppIDbContextProcedures _procedures;

        public virtual ITestAppIDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TestAppIDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITestAppIDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TestAppIDbContextProcedures : ITestAppIDbContextProcedures
    {
        private readonly TestAppIDbContext _context;

        public TestAppIDbContextProcedures(TestAppIDbContext context)
        {
            _context = context;
        }
    }
}
